//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by CNCSewingControl.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   124
#define IDR_MAINFRAME_256               125
#define IDR_CNCSewingContrlTYPE         126
#define ID_WINDOW_MANAGER               127
#define IDS_WINDOWS_MANAGER             128
#define ID_PROPERTIES                   129
#define ID_OPEN                         130
#define ID_OPEN_WITH                    131
#define ID_DUMMY_COMPILE                132
#define ID_NEW_FOLDER                   133
#define ID_SORT_MENU                    134
#define ID_SORTING_GROUPBYTYPE          135
#define ID_SORTING_SORTALPHABETIC       136
#define ID_SORTING_SORTBYTYPE           138
#define ID_SORTING_SORTBYACCESS         139
#define IDR_PASTE_MENU                  140
#define ID_SORTPROPERTIES               141
#define IDR_WINDOWS_MENU                142
#define ID_PROPERTIES1                  143
#define ID_PROPERTIES2                  144
#define ID_EXPAND_ALL                   145
#define IDS_FILE_VIEW                   146
#define IDS_SEWFILE_VIEW                147
#define IDS_SEWINGINFO_VIEW             148
#define IDI_FILE_VIEW                   149
#define IDI_FILE_VIEW_HC                150
#define IDI_CLASS_VIEW                  151
#define IDI_CLASS_VIEW_HC               152
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_RIBBON_FILE                 260
#define IDS_RIBBON_NEW                  262
#define IDS_RIBBON_OPEN                 263
#define IDS_RIBBON_SAVE                 264
#define IDS_RIBBON_SAVEAS               265
#define IDS_RIBBON_PRINT                266
#define IDS_RIBBON_PRINT_LABEL          267
#define IDS_RIBBON_PRINT_QUICK          268
#define IDS_RIBBON_PRINT_PREVIEW        269
#define IDS_RIBBON_PRINT_SETUP          270
#define IDS_RIBBON_CLOSE                271
#define IDS_RIBBON_RECENT_DOCS          272
#define IDS_RIBBON_EXIT                 273
#define IDS_RIBBON_HOME                 274
#define IDS_RIBBON_CLIPBOARD            275
#define IDS_RIBBON_PASTE                276
#define IDS_RIBBON_CUT                  277
#define IDS_RIBBON_COPY                 278
#define IDS_RIBBON_SELECTALL            279
#define IDS_RIBBON_WINDOW               284
#define IDS_RIBBON_WINDOWS              285
#define IDS_RIBBON_STYLE                286
#define IDS_RIBBON_STYLE_TIP            287
#define IDS_RIBBON_STYLE_DESC           288
#define IDS_RIBBON_STATUSBAR            289
#define IDS_RIBBON_VIEW                 290
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_VALUE_SET                   310
#define IDR_SEARCH                      311
#define IDC_CMB_IOCHECK                 312
#define IDC_EDIT_VALUE                  313
#define IDC_BTN_RESET                   314
#define IDC_BTN_PLUS                    315
#define IDC_BTN_MINUS                   316
#define IDC_STATIC_TITLE                317
#define IDC_EDIT_SEARCH                 318
#define IDB_SEWCONTROL_LARGE            326
#define IDI_FILE_MANAGE                 329
#define IDR_FILEMANAGE                  331
#define IDD_FILE_RENAME                 334
#define IDB_BITMAP1                     335
#define IDR_PARACONFIG                  336
#define IDD_CONNECT                     337
#define IDI_FILE_SELECTED               338
#define ID_TIMER_IOCHECK                339
#define IDR_LOCALFILEMANAGE             340
#define IDB_BMP_WAITTING                341
#define IDD_DLG_WAITING                 342
#define ID_VIEW_SEWINGINFO              1001
#define ID_VIEW_SEWFILE                 1002
#define ID_VIEW_IOCHECK                 1003
#define ID_VIEW_PARACONFIG              1004
#define ID_VIEW_FILEMANAGE              1005
#define IDC_LIST_FILE                   1006
#define IDC_CMB_SET_PORT                1007
#define IDC_EDIT_OLDNAME                1008
#define IDC_EDIT_NEWNAME                1009
#define IDC_TREE_FILE                   1010
#define IDC_WAITING_INFO                1011
#define ID_SEW_CONNECT                  2001
#define ID_SEWFILE_SET                  2002
#define ID_PARAM_CONFIG                 2003
#define ID_IO_CHECK                     2004
#define ID_SEW_EDIT                     2005
#define ID_FILE_MANAGE                  2006
#define ID_SEWINGINFO_SET               2007
#define ID_SEW_BREAK                    2008
#define ID_CMD_SAVE                     2009
#define ID_CMD_RETURN                   2010
#define ID_CMD_RECEIVEDATA              2011
#define ID_CMD_GET_PARAMLIST            2012
#define ID_CMD_GET_FILELIST             2013
#define ID_CMD_REQUEST_DELETEFILE       2014
#define ID_PLACE_HOLDER                 2015
#define ID_CMD_DELETE                   2016
#define ID_CMD_COPY                     2017
#define ID_CMD_RENAME                   2018
#define ID_CMD_FILECUT                  2019
#define ID_CMD_SEARCH                   2020
#define ID_CMD_GET_DEVICEINFO           2021
#define ID_CMD_GET_SEWINGINFO           2022
#define ID_CMD_SET_SEWINGINFO           2023
#define ID_CMD_SET_CURRENTSEW           2024
#define ID_CMD_GET_CURRENTSEW           2025
#define ID_CMD_GET_SEWFILEDATA          2026
#define ID_CMD_UPLOAD_SEWFILE           2027
#define ID_CMD_SET_PARAM                2028
#define ID_CMD_REQUEST_INPUTCHECK       2029
#define ID_CMD_REQUEST_OUTPUTCHECK      2030
#define ID_VIEW_FILE_LOCAL              2031
#define ID_CMD_FOLDERRETURN             2032
#define ID_CMD_UPLOADSEW                2033
#define ID_CMD_DOWNLOADSEW              2034
#define ID_CMD_RETURNHOME               2035
#define ID_CMD_RENAME_SEWFILE           2036
#define ID_CMD_REFRESH                  2037
#define ID_TIMER_WAITANSWER             2038
#define ID_CMD_PREVIEW_SEW              2039
#define ID_CMD_SAVE_VALUE               2040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        343
#define _APS_NEXT_COMMAND_VALUE         2041
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
